sudo: required #is required to use docker service in travis
language: node_js
node_js:
  - "7"
services:
  - docker # required, but travis uses older version of docker :
before_script:
  - docker --version
script:
  - mkdir $HOME/compiled # directory to store compiled library
  - cd libamtrackForJs

  # compile with WASM support
  - docker build --build-arg repoUrl=https://github.com/libamtrack/library.git --build-arg branch=forjs --build-arg WASM=1 -t libamtrack/libamtrackforjs:latest .
  - docker run -itd --name libamtrack libamtrack/libamtrackforjs
  - docker cp libamtrack:/libat.js $HOME/compiled
  - docker cp libamtrack:/libat.wasm $HOME/compiled
  - docker container rm -f libamtrack
  - docker image rm -f libamtrackforjs_libamtrack
  - rm -f libat.js
  - rm -f libat.wasm

  # compile without WASM support
  - docker build --build-arg repoUrl=https://github.com/libamtrack/library.git --build-arg branch=forjs --build-arg WASM=0 -t libamtrack/libamtrackforjs:latest .
  - docker run -itd --name libamtrack libamtrack/libamtrackforjs
  - docker cp libamtrack:/libat.js .
  - cp libat.js $HOME/compiled/libatwithoutwasm.js

deploy:
  provider: script
  skip_cleanup: true
  script: bash webRepo.sh # push new version of compiled libraries
  on:
    branch: commit-lib # to test