sudo: required #is required to use docker service in travis
language: node_js
node_js:
  - "7"
services:
  - docker # required, but travis uses older version of docker :
before_script:
  - docker --version
script:
  - sudo mkdir /compiled # directory to store compiled library
  - cd libamtrackForJs

  # compile with WASM support
  - docker build --build-arg repoUrl=https://github.com/libamtrack/library.git --build-arg branch=forjs --build-arg WASM=1 -t libamtrack/libamtrackforjs:latest .
  - docker run -itd --name libamtrack libamtrack/libamtrackforjs
  - sudo docker cp libamtrack:/libat.js /compiled
  - sudo docker cp libamtrack:/libat.wasm /compiled
  - docker container rm -f libamtrack
  - docker image rm -f libamtrackforjs_libamtrack

  # compile without WASM support
  - docker build --build-arg repoUrl=https://github.com/libamtrack/library.git --build-arg branch=forjs --build-arg WASM=0 -t libamtrack/libamtrackforjs:latest .
  - docker run -itd --name libamtrack libamtrack/libamtrackforjs
  - docker cp libamtrack:/libat.js .
  - sudo cp libat.js /compiled/libatwithoutwasm.js

on_success:
  # push new versions of compiled libraries
  - cd /
  - git clone https://github.com/libamtrack/web.git
  - cd /web
  - current_date_time="`date "+%Y%m%d_%H%M%S"`"
  - git checkout -b "feature/compiled_lib/$current_date_time"

  - rm -f /web/src/libat.wasm
  - cp /compiled/libat.wasm /web/src/libat.wasm

  - rm -f /web/src/static/js/libat.js
  - cp /compiled/libat.js /web/src/static/js/libat.js

  - rm -f /web/src/static/js/libatwithoutwasm.js
  - cp /compiled/libatwithoutwasm.js /web/src/static/js/libatwithoutwasm.js

  - git add -A
  - git commit -m "Update compiled library"
  - git push "https://marwin1991:$GH_TOKEN@github.com/libamtrack/web.git"